@JS()
library aws_iot_device_sdk;

import "package:js/js.dart";

/// Declaration file generated by dts-gen
@JS()
external dynamic device(dynamic options);
@JS()
external dynamic jobs(dynamic options);
@JS()
external dynamic thingShadow(dynamic deviceOptions, dynamic thingShadowOptions);
// Module device
/// Circular reference from aws_iot_device_sdk.device
@JS("device.DeviceClient")
external dynamic get DeviceClient;
@JS("device.prepareWebSocketCustomAuthUrl")
external dynamic prepareWebSocketCustomAuthUrl(dynamic options);
@JS("device.prepareWebSocketUrl")
external dynamic prepareWebSocketUrl(dynamic options, dynamic awsAccessId,
    dynamic awsSecretKey, dynamic awsSTSToken);
// Module prepareWebSocketCustomAuthUrl
@JS("device.prepareWebSocketCustomAuthUrl.prototype")
external dynamic /*{
        }*/
    get prototype;
// End module prepareWebSocketCustomAuthUrl

// Module prepareWebSocketUrl
@JS("device.prepareWebSocketUrl.prototype")
external dynamic /*{
        }*/
    get prepareWebSocketUrl_prototype;
// End module prepareWebSocketUrl

// Module prototype
@JS("device.prototype.domain")
external dynamic get domain;
@JS("device.prototype.addListener")
external dynamic addListener(dynamic type, dynamic listener);
@JS("device.prototype.emit")
external dynamic emit(dynamic type,
    [dynamic args1,
    dynamic args2,
    dynamic args3,
    dynamic args4,
    dynamic args5]);
@JS("device.prototype.eventNames")
external dynamic eventNames();
@JS("device.prototype.getMaxListeners")
external dynamic getMaxListeners();
@JS("device.prototype.listenerCount")
external dynamic listenerCount(dynamic type);
@JS("device.prototype.listeners")
external dynamic listeners(dynamic type);
@JS("device.prototype.on")
external dynamic on(dynamic type, dynamic listener);
@JS("device.prototype.once")
external dynamic once(dynamic type, dynamic listener);
@JS("device.prototype.prependListener")
external dynamic prependListener(dynamic type, dynamic listener);
@JS("device.prototype.prependOnceListener")
external dynamic prependOnceListener(dynamic type, dynamic listener);
@JS("device.prototype.removeAllListeners")
external dynamic removeAllListeners(dynamic type,
    [dynamic args1,
    dynamic args2,
    dynamic args3,
    dynamic args4,
    dynamic args5]);
@JS("device.prototype.removeListener")
external dynamic removeListener(dynamic type, dynamic listener);
@JS("device.prototype.setMaxListeners")
external dynamic setMaxListeners(dynamic n);
// Module addListener
@JS("device.prototype.addListener.prototype")
external dynamic /*{
            }*/
    get addListener_prototype;
// End module addListener

// Module emit
@JS("device.prototype.emit.prototype")
external dynamic /*{
            }*/
    get emit_prototype;
// End module emit

// Module eventNames
@JS("device.prototype.eventNames.prototype")
external dynamic /*{
            }*/
    get eventNames_prototype;
// End module eventNames

// Module getMaxListeners
@JS("device.prototype.getMaxListeners.prototype")
external dynamic /*{
            }*/
    get getMaxListeners_prototype;
// End module getMaxListeners

// Module listenerCount
@JS("device.prototype.listenerCount.prototype")
external dynamic /*{
            }*/
    get listenerCount_prototype;
// End module listenerCount

// Module listeners
@JS("device.prototype.listeners.prototype")
external dynamic /*{
            }*/
    get listeners_prototype;
// End module listeners

// Module on
@JS("device.prototype.on.prototype")
external dynamic /*{
            }*/
    get on_prototype;
// End module on

// Module once
@JS("device.prototype.once.prototype")
external dynamic /*{
            }*/
    get once_prototype;
// End module once

// Module prependListener
@JS("device.prototype.prependListener.prototype")
external dynamic /*{
            }*/
    get prependListener_prototype;
// End module prependListener

// Module prependOnceListener
@JS("device.prototype.prependOnceListener.prototype")
external dynamic /*{
            }*/
    get prependOnceListener_prototype;
// End module prependOnceListener

// Module removeAllListeners
@JS("device.prototype.removeAllListeners.prototype")
external dynamic /*{
            }*/
    get removeAllListeners_prototype;
// End module removeAllListeners

// Module removeListener
@JS("device.prototype.removeListener.prototype")
external dynamic /*{
            }*/
    get removeListener_prototype;
// End module removeListener

// Module setMaxListeners
@JS("device.prototype.setMaxListeners.prototype")
external dynamic /*{
            }*/
    get setMaxListeners_prototype;
// End module setMaxListeners

// End module prototype

// End module device

// Module jobs

// Module prototype
@JS("jobs.prototype.domain")
external dynamic get prototype_domain;
@JS("jobs.prototype.addListener")
external dynamic prototype_addListener(dynamic type, dynamic listener);
@JS("jobs.prototype.emit")
external dynamic prototype_emit(dynamic type,
    [dynamic args1,
    dynamic args2,
    dynamic args3,
    dynamic args4,
    dynamic args5]);
@JS("jobs.prototype.eventNames")
external dynamic prototype_eventNames();
@JS("jobs.prototype.getMaxListeners")
external dynamic prototype_getMaxListeners();
@JS("jobs.prototype.listenerCount")
external dynamic prototype_listenerCount(dynamic type);
@JS("jobs.prototype.listeners")
external dynamic prototype_listeners(dynamic type);
@JS("jobs.prototype.on")
external dynamic prototype_on(dynamic type, dynamic listener);
@JS("jobs.prototype.once")
external dynamic prototype_once(dynamic type, dynamic listener);
@JS("jobs.prototype.prependListener")
external dynamic prototype_prependListener(dynamic type, dynamic listener);
@JS("jobs.prototype.prependOnceListener")
external dynamic prototype_prependOnceListener(dynamic type, dynamic listener);
@JS("jobs.prototype.removeAllListeners")
external dynamic prototype_removeAllListeners(dynamic type,
    [dynamic args1,
    dynamic args2,
    dynamic args3,
    dynamic args4,
    dynamic args5]);
@JS("jobs.prototype.removeListener")
external dynamic prototype_removeListener(dynamic type, dynamic listener);
@JS("jobs.prototype.setMaxListeners")
external dynamic prototype_setMaxListeners(dynamic n);
// Module addListener
@JS("jobs.prototype.addListener.prototype")
external dynamic /*{
            }*/
    get prototype_addListener_prototype;
// End module addListener

// Module emit
@JS("jobs.prototype.emit.prototype")
external dynamic /*{
            }*/
    get prototype_emit_prototype;
// End module emit

// Module eventNames
@JS("jobs.prototype.eventNames.prototype")
external dynamic /*{
            }*/
    get prototype_eventNames_prototype;
// End module eventNames

// Module getMaxListeners
@JS("jobs.prototype.getMaxListeners.prototype")
external dynamic /*{
            }*/
    get prototype_getMaxListeners_prototype;
// End module getMaxListeners

// Module listenerCount
@JS("jobs.prototype.listenerCount.prototype")
external dynamic /*{
            }*/
    get prototype_listenerCount_prototype;
// End module listenerCount

// Module listeners
@JS("jobs.prototype.listeners.prototype")
external dynamic /*{
            }*/
    get prototype_listeners_prototype;
// End module listeners

// Module on
@JS("jobs.prototype.on.prototype")
external dynamic /*{
            }*/
    get prototype_on_prototype;
// End module on

// Module once
@JS("jobs.prototype.once.prototype")
external dynamic /*{
            }*/
    get prototype_once_prototype;
// End module once

// Module prependListener
@JS("jobs.prototype.prependListener.prototype")
external dynamic /*{
            }*/
    get prototype_prependListener_prototype;
// End module prependListener

// Module prependOnceListener
@JS("jobs.prototype.prependOnceListener.prototype")
external dynamic /*{
            }*/
    get prototype_prependOnceListener_prototype;
// End module prependOnceListener

// Module removeAllListeners
@JS("jobs.prototype.removeAllListeners.prototype")
external dynamic /*{
            }*/
    get prototype_removeAllListeners_prototype;
// End module removeAllListeners

// Module removeListener
@JS("jobs.prototype.removeListener.prototype")
external dynamic /*{
            }*/
    get prototype_removeListener_prototype;
// End module removeListener

// Module setMaxListeners
@JS("jobs.prototype.setMaxListeners.prototype")
external dynamic /*{
            }*/
    get prototype_setMaxListeners_prototype;
// End module setMaxListeners

// End module prototype

// End module jobs

// Module thingShadow

// Module prototype
@JS("thingShadow.prototype.domain")
external dynamic get thingShadow_prototype_domain;
@JS("thingShadow.prototype.addListener")
external dynamic thingShadow_prototype_addListener(
    dynamic type, dynamic listener);
@JS("thingShadow.prototype.emit")
external dynamic thingShadow_prototype_emit(dynamic type,
    [dynamic args1,
    dynamic args2,
    dynamic args3,
    dynamic args4,
    dynamic args5]);
@JS("thingShadow.prototype.eventNames")
external dynamic thingShadow_prototype_eventNames();
@JS("thingShadow.prototype.getMaxListeners")
external dynamic thingShadow_prototype_getMaxListeners();
@JS("thingShadow.prototype.listenerCount")
external dynamic thingShadow_prototype_listenerCount(dynamic type);
@JS("thingShadow.prototype.listeners")
external dynamic thingShadow_prototype_listeners(dynamic type);
@JS("thingShadow.prototype.on")
external dynamic thingShadow_prototype_on(dynamic type, dynamic listener);
@JS("thingShadow.prototype.once")
external dynamic thingShadow_prototype_once(dynamic type, dynamic listener);
@JS("thingShadow.prototype.prependListener")
external dynamic thingShadow_prototype_prependListener(
    dynamic type, dynamic listener);
@JS("thingShadow.prototype.prependOnceListener")
external dynamic thingShadow_prototype_prependOnceListener(
    dynamic type, dynamic listener);
@JS("thingShadow.prototype.removeAllListeners")
external dynamic thingShadow_prototype_removeAllListeners(dynamic type,
    [dynamic args1,
    dynamic args2,
    dynamic args3,
    dynamic args4,
    dynamic args5]);
@JS("thingShadow.prototype.removeListener")
external dynamic thingShadow_prototype_removeListener(
    dynamic type, dynamic listener);
@JS("thingShadow.prototype.setMaxListeners")
external dynamic thingShadow_prototype_setMaxListeners(dynamic n);
// Module addListener
@JS("thingShadow.prototype.addListener.prototype")
external dynamic /*{
            }*/
    get thingShadow_prototype_addListener_prototype;
// End module addListener

// Module emit
@JS("thingShadow.prototype.emit.prototype")
external dynamic /*{
            }*/
    get thingShadow_prototype_emit_prototype;
// End module emit

// Module eventNames
@JS("thingShadow.prototype.eventNames.prototype")
external dynamic /*{
            }*/
    get thingShadow_prototype_eventNames_prototype;
// End module eventNames

// Module getMaxListeners
@JS("thingShadow.prototype.getMaxListeners.prototype")
external dynamic /*{
            }*/
    get thingShadow_prototype_getMaxListeners_prototype;
// End module getMaxListeners

// Module listenerCount
@JS("thingShadow.prototype.listenerCount.prototype")
external dynamic /*{
            }*/
    get thingShadow_prototype_listenerCount_prototype;
// End module listenerCount

// Module listeners
@JS("thingShadow.prototype.listeners.prototype")
external dynamic /*{
            }*/
    get thingShadow_prototype_listeners_prototype;
// End module listeners

// Module on
@JS("thingShadow.prototype.on.prototype")
external dynamic /*{
            }*/
    get thingShadow_prototype_on_prototype;
// End module on

// Module once
@JS("thingShadow.prototype.once.prototype")
external dynamic /*{
            }*/
    get thingShadow_prototype_once_prototype;
// End module once

// Module prependListener
@JS("thingShadow.prototype.prependListener.prototype")
external dynamic /*{
            }*/
    get thingShadow_prototype_prependListener_prototype;
// End module prependListener

// Module prependOnceListener
@JS("thingShadow.prototype.prependOnceListener.prototype")
external dynamic /*{
            }*/
    get thingShadow_prototype_prependOnceListener_prototype;
// End module prependOnceListener

// Module removeAllListeners
@JS("thingShadow.prototype.removeAllListeners.prototype")
external dynamic /*{
            }*/
    get thingShadow_prototype_removeAllListeners_prototype;
// End module removeAllListeners

// Module removeListener
@JS("thingShadow.prototype.removeListener.prototype")
external dynamic /*{
            }*/
    get thingShadow_prototype_removeListener_prototype;
// End module removeListener

// Module setMaxListeners
@JS("thingShadow.prototype.setMaxListeners.prototype")
external dynamic /*{
            }*/
    get thingShadow_prototype_setMaxListeners_prototype;
// End module setMaxListeners

// End module prototype

// End module thingShadow

